<a href="https://colab.research.google.com/github/AudryBarimbane/Python_Machine_Learning/blob/main/09_sklearn_prepro_encodage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Encodage**

Pour faire des calculs ,une machine a besoin de traiter des valeurs numériques.

Si notre dataset contient des données qualitatives comme des mots ,alors il est indispensable de convertir ces données en valeurs numériques : on parler d'**encodage**.

EN sklearn , il existe 5 transformers d'encodage :

-LabelBinarizer

-LabelEncoder

-MultiLabelBinarizer

-OneHotEncoder

-ordinalEncoder


Il existe 2 types d'encodage :

-Encodage ordinal 

-Encodage OneHot


**Encodage ordinal**

Associe à chaque catégorie ou classe d'une variable à une valeur numérique 

Exemple :
chat     0

chat     0

chien    1

oiseau   2

On dispose pour cela des transformer :LabelEncoder() et OrdinalEncoder()

**LabelEncoder** 

Encode chaque classe de la variable y en une valeur numérique(0,n_classe-1)

Note : la méthode inverse_transform  permet de décoder les données

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [3]:
y = np.array(['chat', 'chien', 'chat', 'oiseau']) 

Le transformer LabelEncoder a été conçu pour encoder la variable y càd qu en principe que ce transformer ne permet que de traiter une seule colonne


In [4]:
encoder = LabelEncoder()
encoder.fit_transform(y)


array([0, 1, 0, 2])

In [5]:
#encoder.classes_

In [6]:
#encoder.transform(y)

In [7]:
encoder.inverse_transform(np.array([0,0,2,2]))

array(['chat', 'chat', 'oiseau', 'oiseau'], dtype='<U6')

**Ordinal Encoder**

Encode les catégories des variables X en valeurs numériques(0,n_classes-1)

X1        X2    

chat      poils        0     1

chien      poils        1    1


chat        poils      0     1


oiseau     plumes      2     0

Note : c'est l'équivalent de LabelEncoder , mais pour les feautures X


**Ordinal Encoder**

In [8]:
#Ordinal Encoder
from sklearn.preprocessing import OrdinalEncoder


In [14]:
X = np.array([['chat','poils'],
              ['chien', 'poils'],
              ['chat','poils'],
              ['oiseau','plumes']])

In [15]:
encoder = OrdinalEncoder()
encoder.fit_transform(X)

array([[0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 0.]])

chat       0

chat       0

chien      1

oiseau     2

chien      1

0 < 1 < 2 

=> chat < chien < oiseau ???  ça n 'a pas de sens 

Cela risque de pénaliser la plupart des modèles , à l'exception des modèles qui sont basés sur les arbres de décision car ceux là ne sont pas sensibles aux relations d'ordres , dans les données qu'on leur présente.
Pour éviter cela , il existe un autre type d'encodage :Encodage **ONE HoT**

**Encodage ONE HOT** 


chat          1  0  0
 
chat          1  0  0

chien         0   1  0

oiseau        0   0  1

chien         0   1  0



Pour faire cela en sklearn , on dispose de 3 transformer :
 -LabelBinarizer()
 -MultiLabelBinarizer()
 -OneHotEncoder()

 


**LABEL BINARIZER**

Encode chaque classe de la variable y en One-Hot

chat          1  0  0
 
chien         0   1  0

chat          1  0  0

oiseau        0   0  1

Note : la méthode inverse_transform  permet de décoder les données 




In [16]:
from sklearn.preprocessing import  LabelBinarizer

In [17]:
y = np.array(['chat', 'chien', 'chat', 'oiseau'])

In [18]:
encoder = LabelBinarizer()
encoder.fit_transform(y)

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

Encodage , One Hot peut présenter un inconvénient , en effet ,
dans le cas où on a un très grand nombre de catégories , on va avoir un tableau extrêment large et difficile à manipuler , mais en réalité , ce n'est pas vraiment un problème.Bien que large , ce tableau ne va pas péser trop lourd sur la mémoire de notre ordinateur.

=> Matrice creuse(sparse matrix) : matrice remplie en grande majorité de 0.
On peut représenter la sparse matrix en format très léger dans lequel , le chiffre 0 n'est tout simplement pas stocké dans la mémoire de l'ordinateur.


Exemple :

a 0 0 0 0
0 0 b 0 0
0 0 0 0 0
0 0 0 0 c
0 0 0 0 0

values = [a,b,c]

rows = [0,1,3]

cols = [0,2,4]
Ce format(values,rows,cols) s'appelle COO
En sklearn , le format qu'on utilise en CSR(compressed sparse row)

In [19]:
#format compressé avec sklearn
encoder = LabelBinarizer(sparse_output=True)
encoder.fit_transform(y)

<4x3 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

**One-Hot Encoder** 

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
# Compressed Sparse Row est le choix par défaut pour OneHotEncoder
encoder =  OneHotEncoder()
encoder.fit_transform(X)


<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

Encoding :
 -encodage ordinal :(y:LabelEncoder , X :OrdinalEncoder)
 
 -encodage one-hot : (y:LabeBinarizer et MutliLabelBinarizer, X:OneHotEncoder)

 Notes :inverse_transform pour vos prédictions 

        sparse=True pour OneHotEncoder

Attention :sklearn v22.0 gère mal les catégories inconnues  
    



In [25]:
y_test = np.array(['poisson'])
encoder.transform(y_test)

ValueError: ignored